// This file was auto-generated by ML.NET Model Builder. 

using System;
using DwImgApiML.Model;

namespace DwImgApiML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            string im = @"C:\Users\user1\Downloads\IMG-20200813-WA0011.jpg";
            string im2 = @"C:\Users\user1\Pictures\avatar.jpg";
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                ImageSource = im,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");
            Console.WriteLine($"ImageSource: {sampleData.ImageSource}");
            Console.WriteLine($"\n\nPredicted Label value {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
